config/routes.rb
Lopet::Application.routes.draw do

  root :to => 'welcome#index'
	match 'home' => 'welcome#home', :as => 'home'

	resources :users
	resources :sessions
	get 'sign_up' => 'users#new', :as => 'sign_up'
	get 'log_out' => 'sessions#destroy', :as => 'log_out'
	get 'log_in' => 'sessions#new', :as => 'log_in'

	resources :admin_sessions
	get 'admin_log_out' => 'admin_sessions#destroy', :as => 'admin_log_out'
	get 'admin_log_in' => 'admin_sessions#new', :as => 'admin_log_in'
		
  resources :tipos do
		resources :derechos
	end
  resources :formularios do
		get 'preview', :on => :member
	end
	resources :derechos do
		resources :formularios
	end

	
	get 'accions' => 'accions#index', :as => 'accions'
	match 'accions/show/:id' => 'accions#show', :as => 'accion'
	match 'accions/edit/:id' => 'accions#edit', :as => 'edit_accion'
	match 'accions/create/:id' => 'accions#create', :as => 'create_accion'
	match 'accions/update/:id' => 'accions#update', :as => 'update_accion'

	get 'generate' => 'generator#generate', :as => 'generate'
	get 'generatex' => 'generator#generate_example', :as => 'generatex'
	

end

app/models/formulario.rb
class Formulario < ActiveRecord::Base
	validates :derecho, :presence=>true
	validates :title, :presence=>true
	has_many :accions
  belongs_to :derecho
end

app/controllers/formularios_controller.rb
class FormulariosController < ApplicationController
	require "RedCloth"

	before_filter :is_admin, :except => [:show]

  # GET /formularios
  # GET /formularios.xml
  def index
    @formularios = Formulario.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @formularios }
    end
  end

  # GET /formularios/1
  # GET /formularios/1.xml
  def show
    @formulario = Formulario.find(params[:id])

		
		
		@formulario.arguments = RedCloth.new(@formulario.arguments).to_html 

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @formulario }
    end
  end

  # GET /formularios/new
  # GET /formularios/new.xml
  def new
		@derecho = Derecho.find(params[:id])
		@derecho.formularios.build()
  end

  # GET /formularios/1/edit
  def edit
    @formulario = Formulario.find(params[:id])
  end

  # POST /formularios
  # POST /formularios.xml
  def create
		@derecho = Derecho.find(params[:derecho_id])
		@formulario = @derecho.formularios.create(params[:formulario])

    respond_to do |format|
      if @formulario.save
        format.html { redirect_to(@formulario, :notice => 'Formulario was successfully created.') }
        format.xml  { render :xml => @formulario, :status => :created, :location => @formulario }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @formulario.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /formularios/1
  # PUT /formularios/1.xml
  def update
    @formulario = Formulario.find(params[:id])

    respond_to do |format|
      if @formulario.update_attributes(params[:formulario])
        format.html { redirect_to(@formulario, :notice => 'Formulario was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @formulario.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /formularios/1
  # DELETE /formularios/1.xml
  def destroy
    @formulario = Formulario.find(params[:id])
    @formulario.destroy

    respond_to do |format|
      format.html { redirect_to(formularios_url) }
      format.xml  { head :ok }
    end
  end

	def preview
    @formulario = Formulario.find(params[:id])
		render :preview, :locals => {:arguments =>
RedCloth.new(@formulario.arguments).to_html}
	end

end

app/helpers/formularios_helper.rb
module FormulariosHelper
end

app/views/formularios/_form.html.erb
<%= form_for(formulario) do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :arguments %><br />
    <%= f.text_area :arguments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/formularios/edit.html.erb
<h1>Editing formulario</h1>

<%= render :partial => "form", :locals => {:formulario => @formulario} %>
<br/>
<%= link_to 'Show', @formulario %> |
<%= link_to 'Back', derecho_path(:id => @formulario.derecho_id ) %>

app/views/formularios/index.html.erb
<h1>Listing formularios</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Arguments</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @formularios.each do |formulario| %>
  <tr>
    <td><%= formulario.title %></td>
    <td><%= formulario.description %></td>
    <td><%= formulario.arguments %></td>
    <td><%= link_to 'Show', formulario %></td>
    <td><%= link_to 'Edit', edit_formulario_path(formulario) %></td>
    <td><%= link_to 'Destroy', formulario, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Formulario', new_formulario_path %>

app/views/formularios/new.html.erb
<h1>New formulario</h1>

<%= render :partial => "form", :locals => {:formulario => [@derecho, @derecho.formularios.build]} %>
<br/>
<%= link_to 'Back', formularios_path %>

app/views/formularios/preview.html.erb
<%= raw arguments %> 
<%= link_to 'back', formulario_path %>

app/views/formularios/show.html.erb
<h3>
  <%= @formulario.title %>
</h3>

<p class="desc">
  <%= @formulario.description %>
</p>

<div class="arguments">
	<%=	raw @formulario.arguments %>
</div>

<br />
<%= link_to 'Edit', edit_formulario_path(@formulario) %> |
<%= link_to 'Back', derecho_path(:id =>@formulario.derecho_id ) %>