config/routes.rb
Lopet::Application.routes.draw do

  root :to => 'welcome#index'
	match 'home' => 'welcome#home', :as => 'home'

	resources :users
	resources :sessions
	get 'sign_up' => 'users#new', :as => 'sign_up'
	get 'log_out' => 'sessions#destroy', :as => 'log_out'
	get 'log_in' => 'sessions#new', :as => 'log_in'

	resources :admin_sessions
	get 'admin_log_out' => 'admin_sessions#destroy', :as => 'admin_log_out'
	get 'admin_log_in' => 'admin_sessions#new', :as => 'admin_log_in'
		
  resources :tipos do
		resources :derechos
	end
  resources :formularios do
		get 'preview', :on => :member
	end
	resources :derechos do
		resources :formularios
	end

	
	get 'accions' => 'accions#index', :as => 'accions'
	match 'accions/show/:id' => 'accions#show', :as => 'accion'
	match 'accions/edit/:id' => 'accions#edit', :as => 'edit_accion'
	match 'accions/create/:id' => 'accions#create', :as => 'create_accion'
	match 'accions/update/:id' => 'accions#update', :as => 'update_accion'

	get 'generate' => 'generator#generate', :as => 'generate'
	get 'generatex' => 'generator#generate_example', :as => 'generatex'
	

end

app/models/accion.rb
class Accion < ActiveRecord::Base
  belongs_to :user
  belongs_to :formulario
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessible :login, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :login
  validates_uniqueness_of :login
  
  def self.authenticate(login, password)
    admin = find_by_login(login)
    if admin && admin.password_hash ==
BCrypt::Engine.hash_secret(password, admin.password_salt)
      admin
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
	end
end

app/models/autoridad.rb
class Autoridad < ActiveRecord::Base
  belongs_to :juez
end

app/models/derecho.rb
class Derecho < ActiveRecord::Base
	validates :title, :presence=>true
	validates :tipo, :presence=>true
  belongs_to :tipo
	has_many :formularios
end

app/models/formulario.rb
class Formulario < ActiveRecord::Base
	validates :derecho, :presence=>true
	validates :title, :presence=>true
	has_many :accions
  belongs_to :derecho
end

app/models/juez.rb
class Juez < ActiveRecord::Base
end

app/models/tipo.rb
class Tipo < ActiveRecord::Base
	validates :title, :presence=>true
	has_many :derechos
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

	has_many :accions
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
	end
end

app/controllers/accions_controller.rb
class AccionsController < ApplicationController

	before_filter :is_user

  # GET /accions
  # GET /accions.xml
  def index
    @accions = Accion.find_all_by_user_id(current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @accions }
    end
  end

  # GET /accions/1
  # GET /accions/1.xml
  def show
    @accion = Accion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @accion }
    end
  end

  # GET /accions/1/edit
  def edit
    @accion = Accion.find(params[:id])
  end

  # POST /accions
  # POST /accions.xml
  def create
    @accion = Accion.new(:formulario_id => params[:id],
:user_id => current_user.id)

    respond_to do |format|
      if @accion.save
        format.html { redirect_to(@accion, :notice => 'Accion was successfully created.') }
        format.xml  { render :xml => @accion, :status => :created, :location => @accion }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @accion.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /accions/1
  # PUT /accions/1.xml
  def update
    @accion = Accion.find(params[:id])

    respond_to do |format|
      if @accion.update_attributes(params[:accion])
        format.html { redirect_to(@accion, :notice => 'Accion was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @accion.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /accions/1
  # DELETE /accions/1.xml
  def destroy
    @accion = Accion.find(params[:id])
    @accion.destroy

    respond_to do |format|
      format.html { redirect_to(accions_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController

	before_filter :is_admin, :except => [:index, :show]

  # GET /tipos
  # GET /tipos.xml
  def index
    @tipos = Tipo.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tipos }
    end
  end

  # GET /tipos/1
  # GET /tipos/1.xml
  def show
    @tipo = Tipo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tipo }
    end
  end

  # GET /tipos/new
  # GET /tipos/new.xml
  def new
    @tipo = Tipo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tipo }
    end
  end

  # GET /tipos/1/edit
  def edit
    @tipo = Tipo.find(params[:id])
  end

  # POST /tipos
  # POST /tipos.xml
  def create
    @tipo = Tipo.new(params[:tipo])

    respond_to do |format|
      if @tipo.save
        format.html { redirect_to(@tipo, :notice => 'Tipo was successfully created.') }
        format.xml  { render :xml => @tipo, :status => :created, :location => @tipo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tipo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tipos/1
  # PUT /tipos/1.xml
  def update
    @tipo = Tipo.find(params[:id])

    respond_to do |format|
      if @tipo.update_attributes(params[:tipo])
        format.html { redirect_to(@tipo, :notice => 'Tipo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tipo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tipos/1
  # DELETE /tipos/1.xml
  def destroy
    @tipo = Tipo.find(params[:id])
    @tipo.destroy

    respond_to do |format|
      format.html { redirect_to(tipos_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
	  @user = User.new
	end

	def create
  	@user = User.new(params[:user])
	  if @user.save
  	  redirect_to root_url, :notice => "Signed up!"
	  else
  	  redirect_to home_path
	  end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

app/helpers/accions_helper.rb
module AccionsHelper
end

app/helpers/admin_sessions_helper.rb
module AdminSessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/autoridads_helper.rb
module AutoridadsHelper
end

app/helpers/derechos_helper.rb
module DerechosHelper
end

app/helpers/formularios_helper.rb
module FormulariosHelper
end

app/helpers/generator_helper.rb
module GeneratorHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accions/_form.html.erb
<%= form_for(@accion) do |f| %>
  <% if @accion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@accion.errors.count, "error") %> prohibited this accion from being saved:</h2>

      <ul>
      <% @accion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hechos %><br />
    <%= f.text_area :hechos %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :formulario %><br />
    <%= f.text_field :formulario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accions/edit.html.erb
<h1>Editing accion</h1>

<!--<%= render 'form' %>-->
<%= form_for :accion, @accion, :url => { :action =>
'update'} do |accion_form| %>
	<%= accion_form.text_area :hechos %>
	<br>
	<%= submit_tag 'Update' %>
<%end%>

	<br>
	<br>
<%= link_to 'Show', @accion %> |
<%= link_to 'Back', accions_path %>

app/views/accions/index.html.erb
<h2>Sus acciónes de tutela</h2>

<% if @accions.count == 0  %>
	no accions
<% else %>
	<ul>
	<% @accions.each do |accion| %>
		<li>
			<%= link_to accion.formulario.title, accion %>
    	<i>(<%= accion.updated_at.strftime("%Y-%m-%d") %>)</i>
		</li>
	<% end %>
	</ul>

<!--
<table>
  <tr>
    <th>Hechos</th>
    <th>User</th>
    <th>Formulario</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @accions.each do |accion| %>
  <tr>
    <td><%= accion.hechos %></td>
    <td><%= accion.user %></td>
    <td><%= accion.formulario.title %></td>
    <td><%= link_to 'Show', accion_path(accion) %></td>
    <td><%= link_to 'Edit', edit_accion_path(accion) %></td>
    <td><%= link_to 'Destroy', accion, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

-->
<br />
<% end %>

app/views/accions/new.html.erb
<h1>New accion</h1>

<%= render 'form' %>

<%= link_to 'Back', accions_path %>

app/views/accions/show.html.erb
<h2>Acción de tutela</h2>

<p>
  <b>Problema:</b>
  <%= @accion.formulario.title %>
</p>

<p>
  <b>Hechos:</b>
  <%= @accion.hechos %>
</p>

<%= link_to 'Edit', edit_accion_path(@accion) %> |
<%= link_to 'Generate', generate_path(:id => @accion.id) %> |
<%= link_to 'Back', accions_path %>

app/views/tipos/_form.html.erb
<%= form_for(@tipo) do |f| %>
  <% if @tipo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipo.errors.count, "error") %> prohibited this tipo from being saved:</h2>

      <ul>
      <% @tipo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipos/edit.html.erb
<h1>Editing tipo</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipo %> |
<%= link_to 'Back', tipos_path %>

app/views/tipos/index.html.erb
<h2>Tipos de derechos fundamentales</h2>

<% if admin %>
	<%= link_to 'New Tipo', new_tipo_path %>
<% end %>

<br />

<ul>
	<% @tipos.each do |tipo| %>
		<li>
			<h3><%= tipo.title %></h3>
			<% if admin %>
				<%= link_to 'Edit', edit_tipo_path(tipo) %> | 
				<%= link_to 'Destroy', tipo, :confirm => 'Are you sure?', :method => :delete %> | 
				<%= link_to 'New derecho', new_derecho_path(:id => tipo.id) %>
				<br />
			<% end %>
			<p class="desc"><%= tipo.description %></p>
			<ul>
				<% tipo.derechos.each do |derecho| %>
					<li> 
						<%= link_to derecho.title, derecho_path(:id =>derecho.id) %>
					</li>
				<% end %>
			</ul>
		</li>
	<% end %>
</ul>

<br />

app/views/tipos/new.html.erb
<h1>New tipo</h1>

<%= render 'form' %>

<%= link_to 'Back', tipos_path %>

app/views/tipos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @tipo.title %>
</p>

<p>
  <b>Description:</b>
  <%= @tipo.description %>
</p>

<p>
  <b>Derechos:</b>
	<ul>
		<% @tipo.derechos.each do |derecho| %>
			<li><%= derecho.title %></li>
		<% end %>
	</ul>
</p>

<%= link_to 'Edit', edit_tipo_path(@tipo) %> |
<%= link_to 'Back', tipos_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>