config/routes.rb
Lopet::Application.routes.draw do

  root :to => 'welcome#index'
	match 'home' => 'welcome#home', :as => 'home'

	resources :users
	resources :sessions
	get 'sign_up' => 'users#new', :as => 'sign_up'
	get 'log_out' => 'sessions#destroy', :as => 'log_out'
	get 'log_in' => 'sessions#new', :as => 'log_in'

	resources :admin_sessions
	get 'admin_log_out' => 'admin_sessions#destroy', :as => 'admin_log_out'
	get 'admin_log_in' => 'admin_sessions#new', :as => 'admin_log_in'
		
  resources :tipos do
		resources :derechos
	end
  resources :formularios do
		get 'preview', :on => :member
	end
	resources :derechos do
		resources :formularios
	end

	
	get 'accions' => 'accions#index', :as => 'accions'
	match 'accions/show/:id' => 'accions#show', :as => 'accion'
	match 'accions/edit/:id' => 'accions#edit', :as => 'edit_accion'
	match 'accions/create/:id' => 'accions#create', :as => 'create_accion'
	match 'accions/update/:id' => 'accions#update', :as => 'update_accion'

	get 'generate' => 'generator#generate', :as => 'generate'
	get 'generatex' => 'generator#generate_example', :as => 'generatex'
	

end

app/models/accion.rb
class Accion < ActiveRecord::Base
  belongs_to :user
  belongs_to :formulario
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessible :login, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :login
  validates_uniqueness_of :login
  
  def self.authenticate(login, password)
    admin = find_by_login(login)
    if admin && admin.password_hash ==
BCrypt::Engine.hash_secret(password, admin.password_salt)
      admin
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
	end
end

app/models/autoridad.rb
class Autoridad < ActiveRecord::Base
  belongs_to :juez
end

app/models/derecho.rb
class Derecho < ActiveRecord::Base
	validates :title, :presence=>true
	validates :tipo, :presence=>true
  belongs_to :tipo
	has_many :formularios
end

app/models/formulario.rb
class Formulario < ActiveRecord::Base
	validates :derecho, :presence=>true
	validates :title, :presence=>true
	has_many :accions
  belongs_to :derecho
end

app/models/juez.rb
class Juez < ActiveRecord::Base
end

app/models/tipo.rb
class Tipo < ActiveRecord::Base
	validates :title, :presence=>true
	has_many :derechos
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

	has_many :accions
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
	end
end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController

	before_filter :is_admin, :except => [:index, :show]

  # GET /tipos
  # GET /tipos.xml
  def index
    @tipos = Tipo.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tipos }
    end
  end

  # GET /tipos/1
  # GET /tipos/1.xml
  def show
    @tipo = Tipo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tipo }
    end
  end

  # GET /tipos/new
  # GET /tipos/new.xml
  def new
    @tipo = Tipo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tipo }
    end
  end

  # GET /tipos/1/edit
  def edit
    @tipo = Tipo.find(params[:id])
  end

  # POST /tipos
  # POST /tipos.xml
  def create
    @tipo = Tipo.new(params[:tipo])

    respond_to do |format|
      if @tipo.save
        format.html { redirect_to(@tipo, :notice => 'Tipo was successfully created.') }
        format.xml  { render :xml => @tipo, :status => :created, :location => @tipo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tipo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tipos/1
  # PUT /tipos/1.xml
  def update
    @tipo = Tipo.find(params[:id])

    respond_to do |format|
      if @tipo.update_attributes(params[:tipo])
        format.html { redirect_to(@tipo, :notice => 'Tipo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tipo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tipos/1
  # DELETE /tipos/1.xml
  def destroy
    @tipo = Tipo.find(params[:id])
    @tipo.destroy

    respond_to do |format|
      format.html { redirect_to(tipos_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
	  @user = User.new
	end

	def create
  	@user = User.new(params[:user])
	  if @user.save
  	  redirect_to root_url, :notice => "Signed up!"
	  else
  	  redirect_to home_path
	  end
  end
end

app/helpers/accions_helper.rb
module AccionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/autoridads_helper.rb
module AutoridadsHelper
end

app/helpers/derechos_helper.rb
module DerechosHelper
end

app/helpers/formularios_helper.rb
module FormulariosHelper
end

app/helpers/generator_helper.rb
module GeneratorHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fácil</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
	<%= favicon_link_tag %>
	<link
href='http://fonts.googleapis.com/css?family=Pacifico&text=fácil/admin' rel='stylesheet' type='text/css'>
	<link
href='http://fonts.googleapis.com/css?family=Maven+Pro:regular,bold' rel='stylesheet' type='text/css'>
</head>
<body>
<div>
	<div id="header_frame">
	<div id="header">
		<span id="logo">fácil <% if admin %> /admin <% end %> </span>

		<div id="user_nav">

			<% if current_user %>
				<b><i><%= current_user.email %></i></b>
				<%= link_to "Log out", log_out_path %>
			<% elsif admin %>
				Logged in as <%= admin.login %>.
				<%= link_to "Log out", admin_log_out_path %>
			<% end %>

		</div>
		
		<% if current_user %>
			<div id="menu">
				<%= link_to 'navigate', tipos_path %>
				<%= link_to 'me', tipos_path%>
				<%= link_to 'accions', accions_path %>
			</div>

		<% elsif admin %>
			<div id="menu">
				<%= link_to 'navigate', tipos_path %>
				<%= link_to 'autoridads', autoridads_path %>
				<%= link_to 'stats', tipos_path %>
			</div>
		<% end %>		
	</div>
	</div>

	<div id="main"/>
		<div id="content">
			<div id="flash">
				<% flash.each do |name, msg| %>
					<%= content_tag :div, msg, :id => "flash_#{name}" %>
				<% end %>
			</div>
			<%= yield %>
		</div>
		<div id="footer">
				
			All rights reserved <%= link_to "Lopet", admin_log_in_path %> & Melisson 2011
		</div>
	</div>
</div>
</body>
</html>